name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: CI                  
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - name: configure
        run: echo "./configure"
      - name: make
        run: echo "make"
      - name: make check
        run: echo "make check"
      - name: make distcheck
        run: echo "make distcheck"
